# Preprocessing data for editing analysis

- Putting things into a centralized dataframe
- Adding a naming schema

In [2]:
import numpy as np 
import pandas as pd
import os

In [38]:
kk = os.listdir('/Volumes/sanchezrivera/samgould/241105SanA/D24-257012-2-6959F_guide_split_BARCODES_redo')
kk

['gRNA_CDK7_targ_1.fastq',
 'gRNA_CDK7_targ_2.fastq',
 'gRNA_CDK7_targ_3.fastq',
 'gRNA_CDK7_targ_4.fastq',
 'gRNA_CDK7_targ_5.fastq',
 'gRNA_CDK7_targ_6.fastq',
 'gRNA_CDK7_targ_7.fastq',
 'gRNA_CDK7_targ_8.fastq',
 'gRNA_CDK7_targ_9.fastq',
 'gRNA_CDK7_targ_10.fastq',
 'gRNA_CDK7_targ_11.fastq',
 'gRNA_CDK7_targ_12.fastq',
 'gRNA_CDK7_targ_13.fastq',
 'gRNA_CDK7_targ_14.fastq',
 'gRNA_CDK7_targ_15.fastq',
 'gRNA_CDK7_targ_16.fastq',
 'gRNA_CDK7_targ_17.fastq',
 'gRNA_CDK7_targ_18.fastq',
 'gRNA_CDK7_targ_19.fastq',
 'gRNA_CDK7_targ_20.fastq',
 'gRNA_CDK7_targ_21.fastq',
 'gRNA_CDK7_targ_22.fastq',
 'gRNA_CDK7_targ_23.fastq',
 'gRNA_CDK7_targ_24.fastq',
 'gRNA_CDK7_targ_25.fastq',
 'gRNA_CDK7_targ_26.fastq',
 'gRNA_CDK7_targ_27.fastq',
 'gRNA_CDK7_targ_28.fastq',
 'gRNA_CDK7_targ_29.fastq',
 'gRNA_CDK7_targ_30.fastq',
 'gRNA_CDK7_targ_31.fastq',
 'gRNA_CDK7_targ_32.fastq',
 'gRNA_CDK7_targ_33.fastq',
 'gRNA_CDK7_targ_34.fastq',
 'gRNA_CDK7_targ_35.fastq',
 'gRNA_CDK7_targ_36.fastq',
 'gRNA_CDK7_targ_37.fastq',
 'gRNA_CDK7_targ_38.fastq',
 'gRNA_CDK7_targ_39.fastq',
 'gRNA_CDK7_targ_40.fastq',
 'gRNA_CDK7_targ_41.fastq',
 'gRNA_CDK7_targ_42.fastq',
 'gRNA_CDK7_targ_43.fastq',
 'gRNA_CDK7_targ_44.fastq',
 'gRNA_CDK7_targ_45.fastq',
 'gRNA_CDK7_targ_46.fastq',
 'gRNA_CDK7_targ_47.fastq',
 'gRNA_CDK7_targ_48.fastq',
 'gRNA_CDK7_targ_49.fastq',
 'gRNA_CDK7_targ_50.fastq',
 'gRNA_CDK7_targ_51.fastq',
 'gRNA_CDK7_targ_52.fastq',
 'gRNA_CDK7_targ_53.fastq',
 'gRNA_CDK7_targ_54.fastq',
 'gRNA_CDK7_targ_55.fastq',
 'gRNA_CDK7_targ_56.fastq',
 'gRNA_CDK7_targ_57.fastq',
 'gRNA_CDK7_targ_58.fastq',
 'gRNA_CDK7_targ_59.fastq',
 'gRNA_CDK7_targ_60.fastq',
 'gRNA_CDK7_targ_61.fastq',
 'gRNA_CDK7_targ_62.fastq',
 'gRNA_CDK7_targ_63.fastq',
 'gRNA_CDK7_targ_64.fastq',
 'gRNA_CDK7_targ_65.fastq',
 'gRNA_CDK7_targ_66.fastq',
 'gRNA_CDK7_targ_67.fastq',
 'gRNA_CDK7_targ_68.fastq',
 'gRNA_CDK7_targ_69.fastq',
 'gRNA_CDK7_targ_70.fastq',
 'gRNA_CDK7_targ_71.fastq',
 'gRNA_CDK7_targ_72.fastq',
 'gRNA_CDK7_targ_73.fastq',
 'gRNA_CDK7_targ_74.fastq',
 'gRNA_CDK7_targ_75.fastq',
 'gRNA_CDK7_targ_76.fastq',
 'gRNA_CDK7_targ_77.fastq',
 'gRNA_CDK7_targ_78.fastq',
 'gRNA_CDK7_targ_79.fastq',
 'gRNA_CDK7_targ_80.fastq',
 'gRNA_CDK7_targ_81.fastq',
 'gRNA_CDK7_targ_82.fastq',
 'gRNA_CDK7_targ_83.fastq',
 'gRNA_CDK7_targ_84.fastq',
 'gRNA_CDK7_targ_85.fastq',
 'gRNA_CDK7_targ_86.fastq',
 'gRNA_CDK7_targ_87.fastq',
 'gRNA_CDK7_targ_88.fastq',
 'gRNA_CDK7_targ_89.fastq',
 'gRNA_CDK7_targ_90.fastq',
 'gRNA_CDK7_targ_91.fastq',
 'gRNA_CDK7_targ_92.fastq',
 'gRNA_CDK7_targ_93.fastq',
 'gRNA_CDK7_targ_94.fastq',
 'gRNA_CDK7_targ_95.fastq',
 'gRNA_CDK7_targ_96.fastq',
 'gRNA_CDK7_targ_97.fastq',
 'gRNA_CDK7_targ_98.fastq',
 'gRNA_CDK7_targ_99.fastq',
 'gRNA_CDK7_targ_100.fastq',
 'gRNA_CDK7_targ_101.fastq',
 'gRNA_CDK7_targ_102.fastq',
 'gRNA_CDK7_targ_103.fastq',
 'gRNA_CDK7_targ_104.fastq',
 'gRNA_CDK7_targ_105.fastq',
 'gRNA_CDK7_targ_106.fastq',
 'gRNA_CDK7_targ_107.fastq',
 'gRNA_CDK7_targ_108.fastq',
 'gRNA_CDK7_targ_109.fastq',
 'gRNA_CDK7_targ_110.fastq',
 'gRNA_CDK7_targ_111.fastq',
 'gRNA_CDK7_targ_112.fastq',
 'gRNA_CDK7_targ_113.fastq',
 'gRNA_CDK7_targ_114.fastq',
 'gRNA_CDK7_targ_115.fastq',
 'gRNA_CDK7_targ_116.fastq',
 'gRNA_CDK7_targ_117.fastq',
 'gRNA_CDK7_targ_118.fastq',
 'gRNA_CDK7_targ_119.fastq',
 'gRNA_CDK7_targ_120.fastq',
 'gRNA_CDK7_targ_121.fastq',
 'gRNA_CDK7_targ_122.fastq',
 'gRNA_CDK7_targ_123.fastq',
 'gRNA_CDK7_targ_124.fastq',
 'gRNA_CDK7_targ_125.fastq',
 'gRNA_CDK7_targ_126.fastq',
 'gRNA_CDK7_targ_127.fastq',
 'gRNA_CDK7_targ_128.fastq',
 'gRNA_CDK7_targ_129.fastq',
 'gRNA_CDK7_targ_130.fastq',
 'gRNA_CDK7_targ_131.fastq',
 'gRNA_CDK7_targ_132.fastq',
 'gRNA_CDK7_targ_133.fastq',
 'gRNA_CDK7_targ_134.fastq',
 'gRNA_CDK7_targ_135.fastq',
 'gRNA_CDK7_targ_136.fastq',
 'gRNA_CDK7_targ_137.fastq',
 'gRNA_CDK7_targ_138.fastq',
 'gRNA_CDK7_targ_139.fastq',
 'gRNA_CDK7_targ_140.fastq',
 'gRNA_CDK7_targ_141.fastq',
 'gRNA_CDK7_targ_142.fastq',
 'gRNA_CDK7_targ_143.fastq',
 'gRNA_CDK7_targ_144.fastq',
 'gRNA_CDK7_targ_145.fastq',
 'gRNA_CDK7_targ_146.fastq',
 'gRNA_CDK7_targ_147.fastq',
 'gRNA_CDK7_targ_148.fastq',
 'gRNA_CDK7_targ_149.fastq',
 'gRNA_CDK7_targ_150.fastq',
 'gRNA_CDK7_targ_151.fastq',
 'gRNA_CDK7_targ_152.fastq',
 'gRNA_CDK7_targ_153.fastq',
 'gRNA_CDK7_targ_154.fastq',
 'gRNA_CDK7_targ_155.fastq',
 'gRNA_CDK7_targ_156.fastq',
 'gRNA_CDK7_targ_157.fastq',
 'gRNA_CDK7_targ_158.fastq',
 'gRNA_CDK7_targ_159.fastq',
 'gRNA_CDK7_targ_160.fastq',
 'gRNA_CDK7_targ_161.fastq',
 'gRNA_CDK7_targ_162.fastq',
 'gRNA_CDK7_targ_163.fastq',
 'gRNA_CDK7_targ_164.fastq',
 'gRNA_CDK7_targ_165.fastq',
 'gRNA_CDK7_targ_166.fastq',
 'gRNA_CDK7_targ_167.fastq',
 'gRNA_CDK7_targ_168.fastq',
 'gRNA_CDK7_targ_169.fastq',
 'gRNA_CDK7_targ_170.fastq',
 'gRNA_CDK7_targ_171.fastq',
 'gRNA_CDK7_targ_172.fastq',
 'gRNA_CDK7_targ_173.fastq',
 'gRNA_CDK7_targ_174.fastq',
 'gRNA_CDK7_targ_175.fastq',
 'gRNA_CDK7_targ_176.fastq',
 'gRNA_CDK7_targ_177.fastq',
 'gRNA_CDK7_targ_178.fastq',
 'gRNA_CDK7_targ_179.fastq',
 'gRNA_CDK7_targ_180.fastq',
 'gRNA_CDK7_targ_181.fastq',
 'gRNA_CDK7_targ_182.fastq',
 'gRNA_CDK7_targ_183.fastq',
 'gRNA_CDK7_targ_184.fastq',
 'gRNA_CDK7_targ_185.fastq',
 'gRNA_CDK7_targ_186.fastq',
 'gRNA_CDK7_targ_187.fastq',
 'gRNA_CDK7_targ_188.fastq',
 'gRNA_CDK7_targ_189.fastq',
 'gRNA_CDK7_targ_190.fastq',
 'gRNA_CDK7_targ_191.fastq',
 'gRNA_CDK7_targ_192.fastq',
 'gRNA_CDK7_targ_193.fastq',
 'gRNA_CDK7_targ_194.fastq',
 'gRNA_CDK7_targ_195.fastq',
 'gRNA_CDK7_targ_196.fastq',
 'gRNA_CDK7_targ_197.fastq',
 'gRNA_CDK7_targ_198.fastq',
 'gRNA_CDK7_targ_199.fastq',
 'gRNA_CDK7_targ_200.fastq',
 'gRNA_nt_8809.fastq',
 'gRNA_CDK7_targ_201.fastq',
 'gRNA_CDK7_targ_202.fastq',
 'gRNA_CDK7_targ_203.fastq',
 'gRNA_CDK7_targ_204.fastq',
 'gRNA_CDK7_targ_205.fastq',
 'gRNA_CDK7_targ_206.fastq',
 'gRNA_CDK7_targ_207.fastq',
 'gRNA_CDK7_targ_208.fastq',
 'gRNA_CDK7_targ_209.fastq',
 'gRNA_CDK7_targ_210.fastq',
 'gRNA_CDK7_targ_211.fastq',
 'gRNA_CDK7_targ_212.fastq',
 'gRNA_CDK7_targ_213.fastq',
 'gRNA_CDK7_targ_214.fastq',
 'gRNA_CDK7_targ_215.fastq',
 'gRNA_CDK7_targ_216.fastq',
 'gRNA_CDK7_targ_217.fastq',
 'gRNA_CDK7_targ_218.fastq',
 'gRNA_CDK7_targ_219.fastq',
 'gRNA_CDK7_targ_220.fastq',
 'gRNA_CDK7_targ_221.fastq',
 'gRNA_CDK7_targ_222.fastq',
 'gRNA_CDK7_targ_223.fastq',
 'gRNA_CDK7_targ_224.fastq',
 'gRNA_CDK7_targ_225.fastq',
 'gRNA_CDK7_targ_226.fastq',
 'gRNA_CDK7_targ_227.fastq',
 'gRNA_CDK7_targ_228.fastq',
 'gRNA_CDK7_targ_229.fastq',
 'gRNA_CDK7_targ_230.fastq',
 'gRNA_CDK7_targ_231.fastq',
 'gRNA_CDK7_targ_232.fastq',
 'gRNA_CDK7_targ_233.fastq',
 'gRNA_CDK7_targ_234.fastq',
 'gRNA_CDK7_targ_235.fastq',
 'gRNA_CDK7_targ_236.fastq',
 'gRNA_CDK7_targ_237.fastq',
 'gRNA_CDK7_targ_238.fastq',
 'gRNA_CDK7_targ_239.fastq',
 'gRNA_CDK7_targ_240.fastq',
 'gRNA_CDK7_targ_241.fastq',
 'gRNA_CDK7_targ_242.fastq',
 'gRNA_CDK7_targ_243.fastq',
 'gRNA_CDK7_targ_244.fastq',
 'gRNA_CDK7_targ_245.fastq',
 'gRNA_CDK7_targ_246.fastq',
 'gRNA_CDK7_targ_247.fastq',
 'gRNA_CDK7_targ_248.fastq',
 'gRNA_CDK7_targ_249.fastq',
 'gRNA_CDK7_targ_250.fastq',
 'gRNA_CDK7_targ_251.fastq',
 'gRNA_CDK7_targ_252.fastq',
 'gRNA_CDK7_targ_253.fastq',
 'gRNA_CDK7_targ_254.fastq',
 'gRNA_CDK7_targ_255.fastq',
 'gRNA_CDK7_targ_256.fastq',
 'gRNA_CDK7_targ_257.fastq',
 'gRNA_CDK7_targ_258.fastq',
 'gRNA_CDK7_targ_259.fastq',
 'gRNA_CDK7_targ_260.fastq',
 'gRNA_CDK7_targ_261.fastq',
 'gRNA_CDK7_targ_262.fastq',
 'gRNA_CDK7_targ_263.fastq',
 'gRNA_CDK7_targ_264.fastq',
 'gRNA_CDK7_targ_265.fastq',
 'gRNA_CDK7_targ_266.fastq',
 'gRNA_CDK7_targ_267.fastq',
 'gRNA_CDK7_targ_268.fastq',
 'gRNA_CDK7_targ_269.fastq',
 'gRNA_CDK7_targ_270.fastq',
 'gRNA_CDK7_targ_271.fastq',
 'gRNA_CDK7_targ_272.fastq',
 'gRNA_CDK7_targ_273.fastq',
 'gRNA_CDK7_targ_274.fastq',
 'gRNA_CDK7_targ_275.fastq',
 'gRNA_CDK7_targ_276.fastq',
 'gRNA_CDK7_targ_277.fastq',
 'gRNA_CDK7_targ_278.fastq',
 'gRNA_CDK7_targ_279.fastq',
 'gRNA_CDK7_targ_280.fastq',
 'gRNA_CDK7_targ_281.fastq',
 'gRNA_CDK7_targ_282.fastq',
 'gRNA_CDK7_targ_283.fastq',
 'gRNA_CDK7_targ_284.fastq',
 'gRNA_CDK7_targ_285.fastq',
 'gRNA_CDK7_targ_286.fastq',
 'gRNA_CDK7_targ_287.fastq',
 'gRNA_CDK7_targ_288.fastq',
 'gRNA_CDK7_targ_289.fastq',
 'gRNA_CDK7_targ_290.fastq',
 'gRNA_CDK7_targ_291.fastq',
 'gRNA_CDK7_targ_292.fastq',
 'gRNA_CDK7_targ_293.fastq',
 'gRNA_CDK7_targ_294.fastq',
 'gRNA_CDK7_targ_295.fastq',
 'gRNA_CDK7_targ_296.fastq',
 'gRNA_CDK7_targ_297.fastq',
 'gRNA_CDK7_targ_298.fastq',
 'gRNA_CDK7_targ_299.fastq',
 'gRNA_CDK7_targ_300.fastq',
 'gRNA_nt_8810.fastq',
 'gRNA_CDK7_targ_301.fastq',
 'gRNA_CDK7_targ_302.fastq',
 'gRNA_CDK7_targ_303.fastq',
 'gRNA_CDK7_targ_304.fastq',
 'gRNA_CDK7_targ_305.fastq',
 'gRNA_CDK7_targ_306.fastq',
 'gRNA_CDK7_targ_307.fastq',
 'gRNA_CDK7_targ_308.fastq',
 'gRNA_CDK7_targ_309.fastq',
 'gRNA_CDK7_targ_310.fastq',
 'gRNA_CDK7_targ_311.fastq',
 'gRNA_CDK7_targ_312.fastq',
 'gRNA_CDK7_targ_313.fastq',
 'gRNA_CDK7_targ_314.fastq',
 'gRNA_CDK7_targ_315.fastq',
 'gRNA_CDK7_targ_316.fastq',
 'gRNA_CDK7_targ_317.fastq',
 'gRNA_CDK7_targ_318.fastq',
 'gRNA_CDK7_targ_319.fastq',
 'gRNA_CDK7_targ_320.fastq',
 'gRNA_CDK7_targ_321.fastq',
 'gRNA_CDK7_targ_322.fastq',
 'gRNA_CDK7_targ_323.fastq',
 'gRNA_CDK7_targ_324.fastq',
 'gRNA_CDK7_targ_325.fastq',
 'gRNA_CDK7_targ_326.fastq',
 'gRNA_CDK7_targ_327.fastq',
 'gRNA_CDK7_targ_328.fastq',
 'gRNA_CDK7_targ_329.fastq',
 'gRNA_CDK7_targ_330.fastq',
 'gRNA_CDK7_targ_331.fastq',
 'gRNA_CDK7_targ_332.fastq',
 'gRNA_CDK7_targ_333.fastq',
 'gRNA_CDK7_targ_334.fastq',
 'gRNA_CDK7_targ_335.fastq',
 'gRNA_CDK7_targ_336.fastq',
 'gRNA_CDK7_targ_337.fastq',
 'gRNA_CDK7_targ_338.fastq',
 'gRNA_CDK7_targ_339.fastq',
 'gRNA_CDK7_targ_340.fastq',
 'gRNA_CDK7_targ_341.fastq',
 'gRNA_CDK7_targ_342.fastq',
 'gRNA_CDK7_targ_343.fastq',
 'gRNA_CDK7_targ_344.fastq',
 'gRNA_CDK7_targ_345.fastq',
 'gRNA_CDK7_targ_346.fastq',
 'gRNA_CDK7_targ_347.fastq',
 'gRNA_CDK7_targ_348.fastq',
 'gRNA_CDK7_targ_349.fastq',
 'gRNA_CDK7_targ_350.fastq',
 'gRNA_CDK7_targ_351.fastq',
 'gRNA_CDK7_targ_352.fastq',
 'gRNA_CDK7_targ_353.fastq',
 'gRNA_CDK7_targ_354.fastq',
 'gRNA_CDK7_targ_355.fastq',
 'gRNA_CDK7_targ_356.fastq',
 'gRNA_CDK7_targ_357.fastq',
 'gRNA_CDK7_targ_358.fastq',
 'gRNA_CDK7_targ_359.fastq',
 'gRNA_CDK7_targ_360.fastq',
 'gRNA_CDK7_targ_361.fastq',
 'gRNA_CDK7_targ_362.fastq',
 'gRNA_CDK7_targ_363.fastq',
 'gRNA_CDK7_targ_364.fastq',
 'gRNA_CDK7_targ_365.fastq',
 'gRNA_CDK7_targ_366.fastq',
 'gRNA_CDK7_targ_367.fastq',
 'gRNA_CDK7_targ_368.fastq',
 'gRNA_CDK7_targ_369.fastq',
 'gRNA_CDK7_targ_370.fastq',
 'gRNA_CDK7_targ_371.fastq',
 'gRNA_CDK7_targ_372.fastq',
 'gRNA_CDK7_targ_373.fastq',
 'gRNA_CDK7_targ_374.fastq',
 'gRNA_CDK7_targ_375.fastq',
 'gRNA_CDK7_targ_376.fastq',
 'gRNA_CDK7_targ_377.fastq',
 'gRNA_CDK7_targ_378.fastq',
 'gRNA_CDK7_targ_379.fastq',
 'gRNA_CDK7_targ_380.fastq',
 'gRNA_CDK7_targ_381.fastq',
 'gRNA_CDK7_targ_382.fastq',
 'gRNA_CDK7_targ_383.fastq',
 'gRNA_CDK7_targ_384.fastq',
 'gRNA_CDK7_targ_385.fastq',
 'gRNA_CDK7_targ_386.fastq',
 'gRNA_CDK7_targ_387.fastq',
 'gRNA_CDK7_targ_388.fastq',
 'gRNA_CDK7_targ_389.fastq',
 'gRNA_CDK7_targ_390.fastq',
 'gRNA_CDK7_targ_391.fastq',
 'gRNA_CDK7_targ_392.fastq',
 'gRNA_CDK7_targ_393.fastq',
 'gRNA_CDK7_targ_394.fastq',
 'gRNA_CDK7_targ_395.fastq',
 'gRNA_CDK7_targ_396.fastq',
 'gRNA_CDK7_targ_397.fastq',
 'gRNA_CDK7_targ_398.fastq',
 'gRNA_CDK7_targ_399.fastq',
 'gRNA_CDK7_targ_400.fastq',
 'gRNA_nt_8811.fastq',
 'gRNA_CDK7_targ_401.fastq',
 'gRNA_CDK7_targ_402.fastq',
 'gRNA_CDK7_targ_403.fastq',
 'gRNA_CDK7_targ_404.fastq',
 'gRNA_CDK7_targ_405.fastq',
 'gRNA_CDK7_targ_406.fastq',
 'gRNA_CDK7_targ_407.fastq',
 'gRNA_CDK7_targ_408.fastq',
 'gRNA_CDK7_targ_409.fastq',
 'gRNA_CDK7_targ_410.fastq',
 'gRNA_CDK7_targ_411.fastq',
 'gRNA_CDK7_targ_412.fastq',
 'gRNA_CDK7_targ_413.fastq',
 'gRNA_CDK7_targ_414.fastq',
 'gRNA_CDK7_targ_415.fastq',
 'gRNA_CDK7_targ_416.fastq',
 'gRNA_CDK7_targ_417.fastq',
 'gRNA_CDK7_targ_418.fastq',
 'gRNA_CDK7_targ_419.fastq',
 'gRNA_CDK7_targ_420.fastq',
 'gRNA_CDK7_targ_421.fastq',
 'gRNA_CDK7_targ_422.fastq',
 'gRNA_CDK7_targ_423.fastq',
 'gRNA_CDK7_targ_424.fastq',
 'gRNA_CDK7_targ_425.fastq',
 'gRNA_CDK7_targ_426.fastq',
 'gRNA_CDK8_targ_427.fastq',
 'gRNA_CDK8_targ_428.fastq',
 'gRNA_CDK8_targ_429.fastq',
 'gRNA_CDK8_targ_430.fastq',
 'gRNA_CDK8_targ_431.fastq',
 'gRNA_CDK8_targ_432.fastq',
 'gRNA_CDK8_targ_433.fastq',
 'gRNA_CDK8_targ_434.fastq',
 'gRNA_CDK8_targ_435.fastq',
 'gRNA_CDK8_targ_436.fastq',
 'gRNA_CDK8_targ_437.fastq',
 'gRNA_CDK8_targ_438.fastq',
 'gRNA_CDK8_targ_439.fastq',
 'gRNA_CDK8_targ_440.fastq',
 'gRNA_CDK8_targ_441.fastq',
 'gRNA_CDK8_targ_442.fastq',
 'gRNA_CDK8_targ_443.fastq',
 'gRNA_CDK8_targ_444.fastq',
 'gRNA_CDK8_targ_445.fastq',
 'gRNA_CDK8_targ_446.fastq',
 'gRNA_CDK8_targ_447.fastq',
 'gRNA_CDK8_targ_448.fastq',
 'gRNA_CDK8_targ_449.fastq',
 'gRNA_CDK8_targ_450.fastq',
 'gRNA_CDK8_targ_451.fastq',
 'gRNA_CDK8_targ_452.fastq',
 'gRNA_CDK8_targ_453.fastq',
 'gRNA_CDK8_targ_454.fastq',
 'gRNA_CDK8_targ_455.fastq',
 'gRNA_CDK8_targ_456.fastq',
 'gRNA_CDK8_targ_457.fastq',
 'gRNA_CDK8_targ_458.fastq',
 'gRNA_CDK8_targ_459.fastq',
 'gRNA_CDK8_targ_460.fastq',
 'gRNA_CDK8_targ_461.fastq',
 'gRNA_CDK8_targ_462.fastq',
 'gRNA_CDK8_targ_463.fastq',
 'gRNA_CDK8_targ_464.fastq',
 'gRNA_CDK8_targ_465.fastq',
 'gRNA_CDK8_targ_466.fastq',
 'gRNA_CDK8_targ_467.fastq',
 'gRNA_CDK8_targ_468.fastq',
 'gRNA_CDK8_targ_469.fastq',
 'gRNA_CDK8_targ_470.fastq',
 'gRNA_CDK8_targ_471.fastq',
 'gRNA_CDK8_targ_472.fastq',
 'gRNA_CDK8_targ_473.fastq',
 'gRNA_CDK8_targ_474.fastq',
 'gRNA_CDK8_targ_475.fastq',
 'gRNA_CDK8_targ_476.fastq',
 'gRNA_CDK8_targ_477.fastq',
 'gRNA_CDK8_targ_478.fastq',
 'gRNA_CDK8_targ_479.fastq',
 'gRNA_CDK8_targ_480.fastq',
 'gRNA_CDK8_targ_481.fastq',
 'gRNA_CDK8_targ_482.fastq',
 'gRNA_CDK8_targ_483.fastq',
 'gRNA_CDK8_targ_484.fastq',
 'gRNA_CDK8_targ_485.fastq',
 'gRNA_CDK8_targ_486.fastq',
 'gRNA_CDK8_targ_487.fastq',
 'gRNA_CDK8_targ_488.fastq',
 'gRNA_CDK8_targ_489.fastq',
 'gRNA_CDK8_targ_490.fastq',
 'gRNA_CDK8_targ_491.fastq',
 'gRNA_CDK8_targ_492.fastq',
 'gRNA_CDK8_targ_493.fastq',
 'gRNA_CDK8_targ_494.fastq',
 'gRNA_CDK8_targ_495.fastq',
 'gRNA_CDK8_targ_496.fastq',
 'gRNA_CDK8_targ_497.fastq',
 'gRNA_CDK8_targ_498.fastq',
 'gRNA_CDK8_targ_499.fastq',
 'gRNA_CDK8_targ_500.fastq',
 'gRNA_nt_8812.fastq',
 'gRNA_CDK8_targ_501.fastq',
 'gRNA_CDK8_targ_502.fastq',
 'gRNA_CDK8_targ_503.fastq',
 'gRNA_CDK8_targ_504.fastq',
 'gRNA_CDK8_targ_505.fastq',
 'gRNA_CDK8_targ_506.fastq',
 'gRNA_CDK8_targ_507.fastq',
 'gRNA_CDK8_targ_508.fastq',
 'gRNA_CDK8_targ_509.fastq',
 'gRNA_CDK8_targ_510.fastq',
 'gRNA_CDK8_targ_511.fastq',
 'gRNA_CDK8_targ_512.fastq',
 'gRNA_CDK8_targ_513.fastq',
 'gRNA_CDK8_targ_514.fastq',
 'gRNA_CDK8_targ_515.fastq',
 'gRNA_CDK8_targ_516.fastq',
 'gRNA_CDK8_targ_517.fastq',
 'gRNA_CDK8_targ_518.fastq',
 'gRNA_CDK8_targ_519.fastq',
 'gRNA_CDK8_targ_520.fastq',
 'gRNA_CDK8_targ_521.fastq',
 'gRNA_CDK8_targ_522.fastq',
 'gRNA_CDK8_targ_523.fastq',
 'gRNA_CDK8_targ_524.fastq',
 'gRNA_CDK8_targ_525.fastq',
 'gRNA_CDK8_targ_526.fastq',
 'gRNA_CDK8_targ_527.fastq',
 'gRNA_CDK8_targ_528.fastq',
 'gRNA_CDK8_targ_529.fastq',
 'gRNA_CDK8_targ_530.fastq',
 'gRNA_CDK8_targ_531.fastq',
 'gRNA_CDK8_targ_532.fastq',
 'gRNA_CDK8_targ_533.fastq',
 'gRNA_CDK8_targ_534.fastq',
 'gRNA_CDK8_targ_535.fastq',
 'gRNA_CDK8_targ_536.fastq',
 'gRNA_CDK8_targ_537.fastq',
 'gRNA_CDK8_targ_538.fastq',
 'gRNA_CDK8_targ_539.fastq',
 'gRNA_CDK8_targ_540.fastq',
 'gRNA_CDK8_targ_541.fastq',
 'gRNA_CDK8_targ_542.fastq',
 'gRNA_CDK8_targ_543.fastq',
 'gRNA_CDK8_targ_544.fastq',
 'gRNA_CDK8_targ_545.fastq',
 'gRNA_CDK8_targ_546.fastq',
 'gRNA_CDK8_targ_547.fastq',
 'gRNA_CDK8_targ_548.fastq',
 'gRNA_CDK8_targ_549.fastq',
 'gRNA_CDK8_targ_550.fastq',
 'gRNA_CDK8_targ_551.fastq',
 'gRNA_CDK8_targ_552.fastq',
 'gRNA_CDK8_targ_553.fastq',
 'gRNA_CDK8_targ_554.fastq',
 'gRNA_CDK8_targ_555.fastq',
 'gRNA_CDK8_targ_556.fastq',
 'gRNA_CDK8_targ_557.fastq',
 'gRNA_CDK8_targ_558.fastq',
 'gRNA_CDK8_targ_559.fastq',
 'gRNA_CDK8_targ_560.fastq',
 'gRNA_CDK8_targ_561.fastq',
 'gRNA_CDK8_targ_562.fastq',
 'gRNA_CDK8_targ_563.fastq',
 'gRNA_CDK8_targ_564.fastq',
 'gRNA_CDK8_targ_565.fastq',
 'gRNA_CDK8_targ_566.fastq',
 'gRNA_CDK8_targ_567.fastq',
 'gRNA_CDK8_targ_568.fastq',
 'gRNA_CDK8_targ_569.fastq',
 'gRNA_CDK8_targ_570.fastq',
 'gRNA_CDK8_targ_571.fastq',
 'gRNA_CDK8_targ_572.fastq',
 'gRNA_CDK8_targ_573.fastq',
 'gRNA_CDK8_targ_574.fastq',
 'gRNA_CDK8_targ_575.fastq',
 'gRNA_CDK8_targ_576.fastq',
 'gRNA_CDK8_targ_577.fastq',
 'gRNA_CDK8_targ_578.fastq',
 'gRNA_CDK8_targ_579.fastq',
 'gRNA_CDK8_targ_580.fastq',
 'gRNA_CDK8_targ_581.fastq',
 'gRNA_CDK8_targ_582.fastq',
 'gRNA_CDK8_targ_583.fastq',
 'gRNA_CDK8_targ_584.fastq',
 'gRNA_CDK8_targ_585.fastq',
 'gRNA_CDK8_targ_586.fastq',
 'gRNA_CDK8_targ_587.fastq',
 'gRNA_CDK8_targ_588.fastq',
 'gRNA_CDK8_targ_589.fastq',
 'gRNA_CDK8_targ_590.fastq',
 'gRNA_CDK8_targ_591.fastq',
 'gRNA_CDK8_targ_592.fastq',
 'gRNA_CDK8_targ_593.fastq',
 'gRNA_CDK8_targ_594.fastq',
 'gRNA_CDK8_targ_595.fastq',
 'gRNA_CDK8_targ_596.fastq',
 'gRNA_CDK8_targ_597.fastq',
 'gRNA_CDK8_targ_598.fastq',
 'gRNA_CDK8_targ_599.fastq',
 'gRNA_CDK8_targ_600.fastq',
 'gRNA_nt_8813.fastq',
 'gRNA_CDK8_targ_601.fastq',
 'gRNA_CDK8_targ_602.fastq',
 'gRNA_CDK8_targ_603.fastq',
 'gRNA_CDK8_targ_604.fastq',
 'gRNA_CDK8_targ_605.fastq',
 'gRNA_CDK8_targ_606.fastq',
 'gRNA_CDK8_targ_607.fastq',
 'gRNA_CDK8_targ_608.fastq',
 'gRNA_CDK8_targ_609.fastq',
 'gRNA_CDK8_targ_610.fastq',
 'gRNA_CDK8_targ_611.fastq',
 'gRNA_CDK8_targ_612.fastq',
 'gRNA_CDK8_targ_613.fastq',
 'gRNA_CDK8_targ_614.fastq',
 'gRNA_CDK8_targ_615.fastq',
 'gRNA_CDK8_targ_616.fastq',
 'gRNA_CDK8_targ_617.fastq',
 'gRNA_CDK8_targ_618.fastq',
 'gRNA_CDK8_targ_619.fastq',
 'gRNA_CDK8_targ_620.fastq',
 'gRNA_CDK8_targ_621.fastq',
 'gRNA_CDK8_targ_622.fastq',
 'gRNA_CDK8_targ_623.fastq',
 'gRNA_CDK8_targ_624.fastq',
 'gRNA_CDK8_targ_625.fastq',
 'gRNA_CDK8_targ_626.fastq',
 'gRNA_CDK8_targ_627.fastq',
 'gRNA_CDK8_targ_628.fastq',
 'gRNA_CDK8_targ_629.fastq',
 'gRNA_CDK8_targ_630.fastq',
 'gRNA_CDK8_targ_631.fastq',
 'gRNA_CDK8_targ_632.fastq',
 'gRNA_CDK8_targ_633.fastq',
 'gRNA_CDK8_targ_634.fastq',
 'gRNA_CDK8_targ_635.fastq',
 'gRNA_CDK8_targ_636.fastq',
 'gRNA_CDK8_targ_637.fastq',
 'gRNA_CDK8_targ_638.fastq',
 'gRNA_CDK8_targ_639.fastq',
 'gRNA_CDK8_targ_640.fastq',
 'gRNA_CDK8_targ_641.fastq',
 'gRNA_CDK8_targ_642.fastq',
 'gRNA_CDK8_targ_643.fastq',
 'gRNA_CDK8_targ_644.fastq',
 'gRNA_CDK8_targ_645.fastq',
 'gRNA_CDK8_targ_646.fastq',
 'gRNA_CDK8_targ_647.fastq',
 'gRNA_CDK8_targ_648.fastq',
 'gRNA_CDK8_targ_649.fastq',
 'gRNA_CDK8_targ_650.fastq',
 'gRNA_CDK8_targ_651.fastq',
 'gRNA_CDK8_targ_652.fastq',
 'gRNA_CDK8_targ_653.fastq',
 'gRNA_CDK8_targ_654.fastq',
 'gRNA_CDK8_targ_655.fastq',
 'gRNA_CDK8_targ_656.fastq',
 'gRNA_CDK8_targ_657.fastq',
 'gRNA_CDK8_targ_658.fastq',
 'gRNA_CDK8_targ_659.fastq',
 'gRNA_CDK8_targ_660.fastq',
 'gRNA_CDK8_targ_661.fastq',
 'gRNA_CDK8_targ_662.fastq',
 'gRNA_CDK8_targ_663.fastq',
 'gRNA_CDK8_targ_664.fastq',
 'gRNA_CDK8_targ_665.fastq',
 'gRNA_CDK8_targ_666.fastq',
 'gRNA_CDK8_targ_667.fastq',
 'gRNA_CDK8_targ_668.fastq',
 'gRNA_CDK8_targ_669.fastq',
 'gRNA_CDK8_targ_670.fastq',
 'gRNA_CDK8_targ_671.fastq',
 'gRNA_CDK8_targ_672.fastq',
 'gRNA_CDK8_targ_673.fastq',
 'gRNA_CDK8_targ_674.fastq',
 'gRNA_CDK8_targ_675.fastq',
 'gRNA_CDK8_targ_676.fastq',
 'gRNA_CDK8_targ_677.fastq',
 'gRNA_CDK8_targ_678.fastq',
 'gRNA_CDK8_targ_679.fastq',
 'gRNA_CDK8_targ_680.fastq',
 'gRNA_CDK8_targ_681.fastq',
 'gRNA_CDK8_targ_682.fastq',
 'gRNA_CDK8_targ_683.fastq',
 'gRNA_CDK8_targ_684.fastq',
 'gRNA_CDK8_targ_685.fastq',
 'gRNA_CDK8_targ_686.fastq',
 'gRNA_CDK8_targ_687.fastq',
 'gRNA_CDK8_targ_688.fastq',
 'gRNA_CDK8_targ_689.fastq',

In [41]:
#load in the editing files
cdk7 = pd.read_csv('edit_libraries/CDK7_edits.csv').rename(columns = {'gRNA_id':'gRNA_id_OLD'})
cdk8 = pd.read_csv('edit_libraries/CDK8_edits.csv').rename(columns = {'gRNA_id':'gRNA_id_OLD'})
cdk9 = pd.read_csv('edit_libraries/CDK9_edits.csv').rename(columns = {'gRNA_id':'gRNA_id_OLD'})
cdk19 = pd.read_csv('edit_libraries/CDK19_edits.csv').rename(columns = {'gRNA_id':'gRNA_id_OLD'})

In [37]:
full_lib = pd.read_csv('CDK_library_CLUSTER.csv')
full_lib = full_lib[['gRNA_id', 'Gene',  'classification', 'Protospacer',  'CBE_amenable','ABE_amenable', 'gRNA_id_OLD']]
full_lib_targeting = full_lib[full_lib['classification']=='targeting']
full_lib_targeting

,gRNA_id,Gene,classification,Protospacer,CBE_amenable,ABE_amenable,gRNA_id_OLD
0,gRNA_CDK7_targ_1,CDK7,targeting,GCGGATGGCTCTGGACGTGA,False,True,gRNA_1
1,gRNA_CDK7_targ_2,CDK7,targeting,GGGCTCTGGACGTGAAGTCT,True,False,gRNA_2
2,gRNA_CDK7_targ_3,CDK7,targeting,GGCTCTGGACGTGAAGTCTC,True,False,gRNA_3
3,gRNA_CDK7_targ_4,CDK7,targeting,GCTCTGGACGTGAAGTCTCG,True,True,gRNA_4
4,gRNA_CDK7_targ_5,CDK7,targeting,GGACGTGAAGTCTCGGGCAA,True,True,gRNA_5
...,...,...,...,...,...,...,...
8472,gRNA_CDK6_targ_8473,CDK6,targeting,GAGGACGGCCTGTGCCGCGC,True,True,gRNA_504
8473,gRNA_CDK6_targ_8474,CDK6,targeting,GAGAAGGACGGCCTGTGCCG,False,True,gRNA_505
8474,gRNA_CDK6_targ_8475,CDK6,targeting,GGGAGAAGGACGGCCTGTGC,False,True,gRNA_506
8475,gRNA_CDK6_targ_8476,CDK6,targeting,GCATGGAGAAGGACGGCCTG,False,True,gRNA_507
8476,gRNA_CDK6_targ_8477,CDK6,targeting,GGGCATGGAGAAGGACGGCC,True,True,gRNA_508

In [70]:
#pulling out CBE edits

cdk7_g = full_lib_targeting[full_lib_targeting['Gene']=='CDK7']
cdk8_g = full_lib_targeting[full_lib_targeting['Gene']=='CDK8']
cdk9_g = full_lib_targeting[full_lib_targeting['Gene']=='CDK9']
cdk19_g = full_lib_targeting[full_lib_targeting['Gene']=='CDK19']

cdk7_merge = pd.merge(cdk7_g, cdk7[cdk7['Editor']=='CBE'], on='gRNA_id_OLD')
cdk8_merge = pd.merge(cdk8_g, cdk8[cdk8['Editor']=='CBE'], on='gRNA_id_OLD')
cdk9_merge = pd.merge(cdk9_g, cdk9[cdk9['Editor']=='CBE'], on='gRNA_id_OLD')
cdk19_merge = pd.merge(cdk19_g, cdk19[cdk19['Editor']=='CBE'], on='gRNA_id_OLD')


#then concatenate and create a new naming schema
concated = pd.concat((cdk7_merge, cdk8_merge, cdk9_merge, cdk19_merge)).reset_index(drop=True)

unique_id = []
for i, val in concated.iterrows():
    gid = val['gRNA_id']
    unique_id.append(f'{gid}_{i+1}')

concated['unique_id'] = unique_id

#and then save it
concated.to_csv('CDK_edits_CBE_pool1.csv', index=False)

In [64]:
concated

,gRNA_id,Gene_x,classification,Protospacer,CBE_amenable_x,ABE_amenable_x,gRNA_id_OLD,edit,Editor,protospacer,...,HGVSp,potential_splice,Complex,MUT_AA,WT_AA,Codon,sensor_wt,sensor_alt,Gene_y,unique_id
0,gRNA_CDK7_targ_2,CDK7,targeting,GGGCTCTGGACGTGAAGTCT,True,False,gRNA_2,TTCTG,CBE,TGGCTCTGGACGTGAAGTCT,...,A2V,False,False,V,A,2.0,ACGCTTTGCCCGAGACTTCACGTCCAGAGCCATCCGGCGCCG,ACGCTTTGCCCGAGACTTCACGTCCAGAACCATCCGGCGCCG,CDK7,gRNA_CDK7_targ_2_1
1,gRNA_CDK7_targ_2,CDK7,targeting,GGGCTCTGGACGTGAAGTCT,True,False,gRNA_2,CTTTG,CBE,TGGCTCTGGACGTGAAGTCT,...,WT,False,False,NaN,NaN,NaN,ACGCTTTGCCCGAGACTTCACGTCCAGAGCCATCCGGCGCCG,ACGCTTTGCCCGAGACTTCACGTCCAAAGCCATCCGGCGCCG,CDK7,gRNA_CDK7_targ_2_2
2,gRNA_CDK7_targ_2,CDK7,targeting,GGGCTCTGGACGTGAAGTCT,True,False,gRNA_2,TTTTG,CBE,TGGCTCTGGACGTGAAGTCT,...,A2V,False,False,V,A,2.0,ACGCTTTGCCCGAGACTTCACGTCCAGAGCCATCCGGCGCCG,ACGCTTTGCCCGAGACTTCACGTCCAAAACCATCCGGCGCCG,CDK7,gRNA_CDK7_targ_2_3
3,gRNA_CDK7_targ_3,CDK7,targeting,GGCTCTGGACGTGAAGTCTC,True,False,gRNA_3,TTTGG,CBE,GGCTCTGGACGTGAAGTCTC,...,WT,False,False,NaN,NaN,NaN,AACGCTTTGCCCGAGACTTCACGTCCAGAGCCATCCGGCGCC,AACGCTTTGCCCGAGACTTCACGTCCAAAGCCATCCGGCGCC,CDK7,gRNA_CDK7_targ_3_4
4,gRNA_CDK7_targ_4,CDK7,targeting,GCTCTGGACGTGAAGTCTCG,True,True,gRNA_4,TTGGA,CBE,GCTCTGGACGTGAAGTCTCG,...,WT,False,False,NaN,NaN,NaN,TAACGCTTTGCCCGAGACTTCACGTCCAGAGCCATCCGGCGC,TAACGCTTTGCCCGAGACTTCACGTCCAAAGCCATCCGGCGC,CDK7,gRNA_CDK7_targ_4_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5140,gRNA_CDK19_targ_6962,CDK19,targeting,GAAGGCGAAGCTGGCGGCGG,True,True,gRNA_735,GGTGA,CBE,CAAGGCGAAGCTGGCGGCGG,...,A7V,False,False,V,A,7.0,CCCGCTCCCGCTCCGCCGCCAGCTTCGCCTTGAAATCATAAT,CCCGCTCCCGCTCCGCCGCCAGCTTCACCTTGAAATCATAAT,CDK19,gRNA_CDK19_targ_6962_5141
5141,gRNA_CDK19_targ_6963,CDK19,targeting,GTCAAGGCGAAGCTGGCGGC,True,True,gRNA_736,AAGGT,CBE,TTCAAGGCGAAGCTGGCGGC,...,A7V,False,False,V,A,7.0,CGCTCCCGCTCCGCCGCCAGCTTCGCCTTGAAATCATAATCC,CGCTCCCGCTCCGCCGCCAGCTTCACCTTGAAATCATAATCC,CDK19,gRNA_CDK19_targ_6963_5142
5142,gRNA_CDK19_targ_6964,CDK19,targeting,GTTCAAGGCGAAGCTGGCGG,True,True,gRNA_737,TAAGG,CBE,TTTCAAGGCGAAGCTGGCGG,...,WT,False,False,NaN,NaN,NaN,GCTCCCGCTCCGCCGCCAGCTTCGCCTTGAAATCATAATCCA,GCTCCCGCTCCGCCGCCAGCTTCGCCTTAAAATCATAATCCA,CDK19,gRNA_CDK19_targ_6964_5143
5143,gRNA_CDK19_targ_6965,CDK19,targeting,GATTTCAAGGCGAAGCTGGC,True,True,gRNA_738,TTTAA,CBE,GATTTCAAGGCGAAGCTGGC,...,WT,False,False,NaN,NaN,NaN,TCCCGCTCCGCCGCCAGCTTCGCCTTGAAATCATAATCCATT,TCCCGCTCCGCCGCCAGCTTCGCCTTAAAATCATAATCCATT,CDK19,gRNA_CDK19_targ_6965_5144
5144,gRNA_CDK19_targ_6966,CDK19,targeting,GGATTTCAAGGCGAAGCTGG,True,True,gRNA_739,TTTTA,CBE,TGATTTCAAGGCGAAGCTGG,...,WT,False,False,NaN,NaN,NaN,CCCGCTCCGCCGCCAGCTTCGCCTTGAAATCATAATCCATTG,CCCGCTCCGCCGCCAGCTTCGCCTTAAAATCATAATCCATTG,CDK19,gRNA_CDK19_targ_6966_5145

In [121]:
jj = os.listdir('/Volumes/sanchezrivera/samgould/241105SanA/crispresso/D24-257003-2-6959F_guide_split_BARCODES_redo/')

len(jj)

1914

In [116]:
pd.read_csv('/Volumes/sanchezrivera/samgould/241105SanA/crispresso/D24-257003-1-6959F_guide_split_BARCODES_redo/CRISPResso_on_gRNA_CDK8_targ_651_1000/Alleles_frequency_table.zip', sep='\t')[:20]

,Aligned_Sequence,Reference_Sequence,Reference_Name,Read_Status,n_deleted,n_inserted,n_mutated,#Reads,%Reads
0,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,UNMODIFIED,0,0,0,355,46.163849
1,AGGTAATTCGATTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,180,23.407022
2,AGGTAATTCGATTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,Reference,MODIFIED,0,0,1,34,4.421326
3,AGGTAATTCGTTTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,32,4.161248
4,AGGTAATTCGGTTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,28,3.641092
5,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,Reference,UNMODIFIED,0,0,0,19,2.470741
6,AGGTAATTCGCTTTATTGGGTCCATCATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,11,1.430429
7,AGGTAATTCGATTTATTGGGTCCATCATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,2,9,1.170351
8,AGGTAATTCGCTTTATTGGGTCCATATTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,9,1.170351
9,AGGTAATTCGTTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,Reference,MODIFIED,0,0,1,8,1.040312
10,AGGTAATTCGCTTTATTGAGTCCATAGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AMBIGUOUS_Reference,MODIFIED,0,0,2,7,0.910273
11,AGGTAATTCGATTTATTGAGTCCATAGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AMBIGUOUS_Reference,MODIFIED,0,0,3,6,0.780234
12,AGGTAATTCGCTTTATTGAGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,4,0.520156
13,ATGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,UNMODIFIED,0,0,0,4,0.520156
14,AGGTAATTCGATTTATTGGGTCCATAATAAGCAGATTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,2,3,0.390117
15,AGGTAATTCGCTTTATTGCGTCCATAGTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA,AMBIGUOUS_Reference,MODIFIED,0,0,2,3,0.390117
16,AGGTAATTCGATTTATTGGGTCCATATTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,2,3,0.390117
17,AGGTAATTCGCTTTATTGGGTACATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,3,0.390117
18,ATGTAATTCGATTTATTGGGTCCATATTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,2,2,0.260078
19,AGGTAATTCGCTTTATTGGGTCCATACTAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,HDR,MODIFIED,0,0,1,2,0.260078

In [119]:
concated[concated['unique_id']=='gRNA_CDK8_targ_651_1000'][['ideal_window', 'edit', 'HGVSp', 'sensor_alt', 'sensor_wt']]

,ideal_window,edit,HGVSp,sensor_alt,sensor_wt
999,TACCA,TATTA,T317I,AGGTAATTCGCTTTATTGGGTCCATAATAAGCAGCTTCTGAA,AGGTAATTCGCTTTATTGGGTCCATGGTAAGCAGCTTCTGAA

In [123]:
concated['unique_id']

0              gRNA_CDK7_targ_2_1
1              gRNA_CDK7_targ_2_2
2              gRNA_CDK7_targ_2_3
3              gRNA_CDK7_targ_3_4
4              gRNA_CDK7_targ_4_5
                  ...
5140    gRNA_CDK19_targ_6962_5141
5141    gRNA_CDK19_targ_6963_5142
5142    gRNA_CDK19_targ_6964_5143
5143    gRNA_CDK19_targ_6965_5144
5144    gRNA_CDK19_targ_6966_5145
Name: unique_id, Length: 5145, dtype: object