# Off-target analysis

Using Cas-OFFinder: http://www.rgenome.net/cas-offinder/

- Up to 4 mismatches allowed
- No DNA or RNA bulges
- XCas9 3.7 (TLIKDIV SpCas9) from Streptococcus pyogenes: 5'-NG-3'
- hg38

In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt 
import scipy.stats
import os
from adjustText import adjust_text
import matplotlib.patheffects as PathEffects
import warnings
warnings.filterwarnings('ignore')
plt.rc('font', family='Helvetica')

In [19]:
#submitting in batches of 1000 gRNAs
library = pd.read_csv('../../source_data/02_library/CDK_library_final.csv')
protos = [i[1:] for i in library['proto_G+19']]

proto_list = list(np.unique(protos))
batch1 = proto_list[:1000]
batch2 = proto_list[1000:2000]
batch3 = proto_list[2000:3000]
batch4 = proto_list[3000:4000]
batch5 = proto_list[4000:5000]
batch6 = proto_list[5000:6000]
batch7 = proto_list[6000:7000]
batch8 = proto_list[7000:8000]
batch9 = proto_list[8000:9000]
batch10 = proto_list[9000:]

for i in batch10:
    print(i)

TTTTACTATGTAACTGTGT
TTTTACTCTTCCTCGCTCA
TTTTACTGAAATATTTCCT
TTTTAGCTGACATGGGTTT
TTTTAGGCCTCTTTTTCGT
TTTTAGTAAGTCCCGGGAA
TTTTAGTGTATTTGCCGGC
TTTTATATGGTTGCTGAGG
TTTTATCCCAGCCTGAAGC
TTTTATTCTTGTTCAATTC
TTTTATTTAGCTGCTGTTG
TTTTCAGGTGTGGAATAGC
TTTTCATCTAGCAACAAGT
TTTTCATTAAAATGAACCA
TTTTCCAATTTTACACTTC
TTTTCCAGACCGTCTGGTG
TTTTCCATAAGCAGAAGAC
TTTTCCATATACTTGATAA
TTTTCCTTTTTATTGCCAA
TTTTCGAGAAGTTTTGGAT
TTTTCGATGACTTTTACTC
TTTTCGTACAGCTCATAGT
TTTTCTAGGCAAAAATACA
TTTTCTCTTTAAGAGATAC
TTTTCTGAGGACCATATCA
TTTTCTTTGCACCTTTCCA
TTTTCTTTGGTTTCACCAT
TTTTGACTCTCCCCCTCTC
TTTTGAGGGTTCCACATCT
TTTTGATTTCACGAATGGC
TTTTGGAAGTTCTCCATGA
TTTTGGACTAAACAATAAA
TTTTTAAAGTTCCACCACT
TTTTTACTCTTCCTCGCTC
TTTTTCACTGTCGTCAGGA
TTTTTCCATATACTTGATA
TTTTTCGTGGAAGTTCAGA
TTTTTGAATTTCTGCACCA

# Processing output

In [22]:
b1 = pd.read_csv('../../source_data/17_off-targets/batch1.txt', sep='\t')

b1[b1['Mismatches']==0]

,#Bulge type,crRNA,DNA,Chromosome,Position,Direction,Mismatches,Bulge Size
16459,X,AAACCAGCCTGGCCCACATNG,AAACCAGCCTGGCCCACATGG,chr8,10957148,-,0,0
17051,X,AAACCAGCCTGGCCCACATNG,AAACCAGCCTGGCCCACATGG,chr8,13456656,-,0,0
17686,X,AAACCAGCCTGGCCCACATNG,AAACCAGCCTGGCCCACATGG,chr8,29239860,-,0,0
17808,X,AAACCAGCCTGGCCCACATNG,AAACCAGCCTGGCCCACATGG,chr8,98707937,+,0,0
52907,X,AACCTGCACATTCTACACANG,AACCTGCACATTCTACACATG,chr8,4320394,-,0,0
...,...,...,...,...,...,...,...,...
1178987,X,ACCATCCTGGCCAATGTGGNG,ACCATCCTGGCCAATGTGGTG,chr3,119454590,+,0,0
1178988,X,ACCATCCTGGCCAATGTGGNG,ACCATCCTGGCCAATGTGGTG,chr3,153651867,+,0,0
1178989,X,ACCATCCTGGCCAATGTGGNG,ACCATCCTGGCCAATGTGGTG,chr3,165171007,+,0,0
1178990,X,ACCATCCTGGCCAATGTGGNG,ACCATCCTGGCCAATGTGGTG,chr3,174697890,+,0,0
1178991,X,ACCATCCTGGCCAATGTGGNG,ACCATCCTGGCCAATGTGGTG,chr3,183665549,+,0,0

In [28]:
u, c = np.unique(b1[b1['Mismatches']==0]['crRNA'], return_counts=True)

np.unique(c, return_counts=True)

(array([   1,    2,    4,   40,   76,  231, 1000]),
 array([923,  43,   1,   1,   1,   1,   1]))

In [33]:
pd.DataFrame(dict(zip(['u', 'c'], [u,c]))).sort_values(by='c', ascending=False)[:30]

                         u     c
967  ACTTGAGGTCAGGAGTTTGNG  1000
719  ACCATCCTGGCCAATGTGGNG   231
215  AACCTGCACATTCTACACANG    76
47   AAACCAGCCTGGCCCACATNG    40
796  ACCTGTAATACCAATACTTNG     4
77   AAAGATTTCAGAAGAAATANG     2
131  AAATGTCACATAATCTGGANG     2
97   AAAGTAAGGATTTAACCATNG     2
572  ACACCAACTGAGGAACAGTNG     2
568  ACACAGGGACCCCCGTTGANG     2
432  AAGTCATCCAAATATAATTNG     2
78   AAAGCAAATAAAAAGCCCANG     2
970  ACTTGTTGCTAGATGAAAANG     2
439  AAGTTAAACCAGATAGTAANG     2
646  ACATCCAGGTGTTGGCCCTNG     2
912  ACTGAAAATGAAGTATTTCNG     2
913  ACTGAAATACTTCATTTTCNG     2
60   AAAGAAAAAGATATTGACTNG     2
58   AAACTGGCAGATTTTGGCCNG     2
457  AATAAGAATAAGCCTTGTANG     2
381  AAGGATAATAGTCTTGTGCNG     2
183  AACATTCAACATTAATGAANG     2
654  ACATGCAGAATATATTGGCNG     2
311  AAGAGGGGGAAGAGGGAGANG     2
263  AACTGGCAGATTTTGGCCTNG     2
269  AACTTGGACATAGATCAGANG     2
733  ACCCCCGTTGAAGAAAGTGNG     2
278  AAGAACCAGCAGCAGCAGCNG     2
279  AAGAACCTGATGACAAAGGNG     2
282  AAGAAGAACCTGATGACAANG     2

In [39]:
library[library['proto_G+19']=='GACCTGTAATACCAATACTT']

,gRNA_id,Gene,protospacer,proto_G+19,chrom,exon,proto_start,proto_end,PAM,PAM_start,...,CDS_hit,ABE_amenable,CBE_amenable,classification,nearest_exon_distance,Pool,Hamming_BC,gRNA_oligo,RE_sites,gRNA_id_OLD
8749,gRNA_CDK2_intron_8750,CDK2,CACCTGTAATACCAATACTT,GACCTGTAATACCAATACTT,12.0,intron4_5,55969125.0,55969144.0,TG,55969145.0,...,NaN,NaN,NaN,intron,196.0,F3-R3,CCCAAGCCTATGT,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGACCTGT...,2,NaN

In [25]:
len(np.unique(b1['crRNA']))

1000