In [16]:
import pandas as pd 
import numpy as np

In [20]:
colony_seq = pd.read_csv('colony_seq_analysis.csv')
library = pd.read_csv('/Users/samgould/Documents/GitHub/CDK9-mutagenesis/CDK_library_final.csv')

In [21]:
library

,gRNA_id,Gene,protospacer,proto_G+19,chrom,exon,proto_start,proto_end,PAM,PAM_start,...,CDS_hit,ABE_amenable,CBE_amenable,classification,nearest_exon_distance,Pool,Hamming_BC,gRNA_oligo,RE_sites,gRNA_id_OLD
0,gRNA_CDK7_targ_1,CDK7,CCGGATGGCTCTGGACGTGA,GCGGATGGCTCTGGACGTGA,5.0,1,69234972.0,69234991.0,AG,69234992.0,...,True,True,False,targeting,NaN,F1-R1,CACATACGCACTA,AGGCACTTGCTCGTACGACGAGCGTACACGTCTCACACCGCGGATG...,2,gRNA_1
1,gRNA_CDK7_targ_2,CDK7,TGGCTCTGGACGTGAAGTCT,GGGCTCTGGACGTGAAGTCT,5.0,1,69234977.0,69234996.0,CG,69234997.0,...,True,False,True,targeting,NaN,F1-R1,CCTATACCCGAAT,AGGCACTTGCTCGTACGACGAGCGTACACGTCTCACACCGGGCTCT...,2,gRNA_2
2,gRNA_CDK7_targ_3,CDK7,GGCTCTGGACGTGAAGTCTC,GGCTCTGGACGTGAAGTCTC,5.0,1,69234978.0,69234997.0,GG,69234998.0,...,True,False,True,targeting,NaN,F1-R1,TATACAATTCGCA,AGGCACTTGCTCGTACGACGAGCGTACACGTCTCACACCGGCTCTG...,2,gRNA_3
3,gRNA_CDK7_targ_4,CDK7,GCTCTGGACGTGAAGTCTCG,GCTCTGGACGTGAAGTCTCG,5.0,1,69234979.0,69234998.0,GG,69234999.0,...,True,True,True,targeting,NaN,F1-R1,CCGGAGTAGGTCC,AGGCACTTGCTCGTACGACGAGCGTACACGTCTCACACCGCTCTGG...,2,gRNA_4
4,gRNA_CDK7_targ_5,CDK7,GGACGTGAAGTCTCGGGCAA,GGACGTGAAGTCTCGGGCAA,5.0,1,69234984.0,69235003.0,AG,69235004.0,...,True,True,True,targeting,NaN,F1-R1,ATTGCAAGGGCCC,AGGCACTTGCTCGTACGACGAGCGTACACGTCTCACACCGGACGTG...,2,gRNA_5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9248,gRNA_nt_9249,NaN,GATCTGTCCTAATTCGGATCG,GTCTGTCCTAATTCGGATCG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,non-targeting control,NaN,F3-R3,TAACTACGAGCTA,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGTCTGTC...,2,NaN
9249,gRNA_nt_9250,NaN,GTGCGGCGTAATGCTTGAAAG,GGCGGCGTAATGCTTGAAAG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,non-targeting control,NaN,F3-R3,TGCAAGTTACCCA,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGGCGGCG...,2,NaN
9250,gRNA_nt_9251,NaN,GGCCGTGTTGCTGGATACGCC,GCCGTGTTGCTGGATACGCC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,non-targeting control,NaN,F3-R3,TGATGCATGCACC,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGCCGTGT...,2,NaN
9251,gRNA_nt_9252,NaN,GTACCCTCCGGATACGGACTG,GACCCTCCGGATACGGACTG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,non-targeting control,NaN,F3-R3,AACCGATGCCGGT,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGACCCTC...,2,NaN
9252,gRNA_nt_9253,NaN,GCCGTTGGACTATGGCGGGTC,GCGTTGGACTATGGCGGGTC,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,non-targeting control,NaN,F3-R3,GGTGCAAGAACGC,CAGCGCCAATGGGCTTTCGAAGCGTACACGTCTCACACCGCGTTGG...,2,NaN

In [22]:
proto_id = []
bc_id = []
proto_pool = []
bc_pool = []
bc_predicted = []
for i, val in colony_seq.iterrows():
    p = val['Protospacer']
    b = val['Barcode']

    proto = library.loc[library['proto_G+19']==p, 'gRNA_id']
    bc = library.loc[library['Hamming_BC']==b, 'gRNA_id']

    if len(proto)!=0:
        proto_id.append(proto.values[0])
        proto_pool.append(library.loc[library['proto_G+19']==p, 'Pool'].values[0])
        bc_predicted.append(library.loc[library['proto_G+19']==p, 'Hamming_BC'].values[0])
    elif len(proto)==0:
        proto_id.append(None)
        proto_pool.append(None)
        bc_predicted.append(None)

    if len(bc)!=0:
        bc_id.append(bc.values[0])
        bc_pool.append(library.loc[library['Hamming_BC']==b, 'Pool'].values[0])
    elif len(bc)==0:
        bc_id.append(None)
        bc_pool.append(None)

In [23]:
colony_seq['barcode_predicted'] = bc_predicted
colony_seq['proto_id'] = proto_id
colony_seq['bc_id'] = bc_id
colony_seq['proto_pool'] = proto_pool
colony_seq['bc_pool'] = bc_pool


match = []

for i, val in colony_seq.iterrows():
    if val['proto_id']==val['bc_id']:
        match.append(True)
    else:
        match.append(False)

colony_seq['proto_bc_match'] = match
colony_seq

,Sample ID,Protospacer,Barcode,barcode_predicted,proto_id,bc_id,proto_pool,bc_pool,proto_bc_match
0,CDK1_1,GGGGAAGCTGAGGCAGGAAT,CAGCATATCCTAC,AGGGTCAGCTAAG,gRNA_CDK9_targ_1458,gRNA_CDK7_targ_407,F1-R1,F1-R1,False
1,CDK1_2,GGGCAGGGTCCAGCACCAGC,TACTCCGGCTCGT,TACTCCGGCTCGT,gRNA_CDK9_targ_1650,gRNA_CDK9_targ_1650,F1-R1,F1-R1,True
2,CDK1_3,GAGCTGACATGGGCTTTGCC,CGAAATCGAGAGG,CCGAATAGAACAA,gRNA_CDK8_targ_571,gRNA_CDK9_targ_1396,F1-R1,F1-R1,False
3,CDK1_4,GTTCAGTCTACGGGCGCGGG,ACGGGCAGGCAGG,None,None,gRNA_nt_8894,None,F1-R1,False
4,CDK1_5,GCCCCGGAGCTGTTGCTCGG,TCGGATGCCTGAG,GTTACTGGTGTAG,gRNA_CDK9_targ_1239,gRNA_CDK19_targ_6920,F1-R1,F1-R1,False
5,CDK1_6,GCTCACCTGTCCCTCCCCAA,TGGATAGATAGGC,TGGATAGATAGGC,gRNA_CDK7_targ_240,gRNA_CDK7_targ_240,F1-R1,F1-R1,True
6,CDK1_7,GCAGGTCCTCGACCCGCTCC,CAGGGTTACGTTA,CCAAATCTTGAAT,gRNA_CDK8_targ_753,gRNA_CDK8_targ_713,F1-R1,F1-R1,False
7,CDK1_8,GAACAAGAAGCCACGGCTAG,GCCGATAGTTCTC,GCCGATAGTTCTC,gRNA_CDK19_targ_6639,gRNA_CDK19_targ_6639,F1-R1,F1-R1,True
8,CDK1_9,GCAGCTGACATCCAGGTGTT,CNNCCTCTATACT,CCGCCTCTATACT,gRNA_CDK7_targ_397,None,F1-R1,None,False
9,CDK1_10,GCTAGGATGTATGGTGTAGG,GGCAGGAGTATTC,GGCAGGAGTATTC,gRNA_CDK7_targ_131,gRNA_CDK7_targ_131,F1-R1,F1-R1,True
10,CDK1_11,GACCCAGTTAGCATGCAGGT,TGAATGCCATGCT,CGTGGGTCTACTT,gRNA_CDK8_targ_824,gRNA_CDK8_targ_1035,F1-R1,F1-R1,False
11,CDK1_14,GACGTTTGGCCACACCTGGG,CTGGAACTATCAT,CTGGAACTATCAT,gRNA_CDK9_targ_1617,gRNA_CDK9_targ_1617,F1-R1,F1-R1,True
12,CDK1_15,GAGTCCATTGTCACAGCCTC,GATTTCACCACAG,ATTGCTAGCATGA,gRNA_CDK8_targ_745,gRNA_CDK8_targ_1026,F1-R1,F1-R1,False
13,CDK2_2,GGGCCTGAGCTGGGCGGAGA,CTCTATGTGCGAA,CTCTATGTGCGAA,gRNA_CDK13_targ_3975,gRNA_CDK13_targ_3975,F2-R2,F2-R2,True
14,CDK2_6,GTGACCCCGCTGGTGGAATA,CACGCCACAGCCA,CACGCCACAGCCA,gRNA_CDK13_targ_4114,gRNA_CDK13_targ_4114,F2-R2,F2-R2,True
15,CDK2_10,GTATTTTATTTAGCTGCTGT,CGGTTCCTCAAGA,CGGTTCCTCAAGA,gRNA_CDK13_targ_5997,gRNA_CDK13_targ_5997,F2-R2,F2-R2,True
16,CDK2_14,GTAAAGATTTGAAAGCACAG,CATTCAGATTAAG,ATGATTAGCTATG,gRNA_CDK12_targ_2109,gRNA_CDK12_targ_2620,F2-R2,F2-R2,False
17,CDK3_1,GCGCGATGCACTACTCGGTG,ACGGCAGCATCGG,ACGGCAGCATCGG,gRNA_CDK6_targ_8121,gRNA_CDK6_targ_8121,F3-R3,F3-R3,True
18,CDK3_2,GCCGGAGTGAGCAATGGAGT,CCTTGCAACCATC,CCTTGCAACCATC,gRNA_CDK4_targ_7699,gRNA_CDK4_targ_7699,F3-R3,F3-R3,True
19,CDK3_3,GCTGAATGGATGTGGCAACA,TACCTGACGCGTC,TACCTGACGCGTC,gRNA_CDK6_intron_8799,gRNA_CDK6_intron_8799,F3-R3,F3-R3,True
20,CDK3_4,GTTGATCGTTTCGGCTGGCA,TTGCCCTGTCAAA,TTGCCCTGTCAAA,gRNA_CDK4_targ_7612,gRNA_CDK4_targ_7612,F3-R3,F3-R3,True
21,CDK3_5,GGGCTGCATCTTTGCTGAGA,TGAGTTAAGTTGC,TGAGTTAAGTTGC,gRNA_CDK2_targ_7108,gRNA_CDK2_targ_7108,F3-R3,F3-R3,True
22,CDK3_6,GAGATGGCTCTAACCTCAGT,CCAATACGCACGC,GAGTACGGCGCGA,gRNA_CDK6_targ_8327,gRNA_CDK4_targ_7686,F3-R3,F3-R3,False
23,CDK3_7,GGAATGGCTACCTCTCGATA,CATGAGGTTCTCA,CATGAGGTTCTCA,gRNA_CDK4_targ_7974,gRNA_CDK4_targ_7974,F3-R3,F3-R3,True
24,CDK3_8,GACTTTACTAAAATCTTGCC,CAGGAGTAGCACA,GACTCCAAACAGA,gRNA_CDK2_targ_7398,gRNA_CDK4_targ_7481,F3-R3,F3-R3,False
25,CDK3_9,GCACCTCGCGGATGGTGGAG,AGTCAGAGGATTA,AGTCAGAGGATTA,gRNA_CDK6_targ_8175,gRNA_CDK6_targ_8175,F3-R3,F3-R3,True
26,CDK3_10,GCTCACGAACTGTGCTGATG,GGTGTTAAGGAAG,CGGCTTGACCTAA,gRNA_CDK4_targ_7659,gRNA_CDK6_targ_8410,F3-R3,F3-R3,False
27,CDK3_11,GAGGCAGCCCAATCAGGCTG,CCTTATGCGCAGA,CCTTATGCGCAGA,gRNA_CDK4_targ_7513,gRNA_CDK4_targ_7513,F3-R3,F3-R3,True
28,CDK3_13,GAATAAAACTCGCTGACTTC,TTCGGATGGCGAT,AACTACTCCCAAT,gRNA_CDK6_targ_8336,gRNA_CDK4_intron_8768,F3-R3,F3-R3,False
29,CDK3_14,GTCCACCATCCGCGAGGTGG,GGGCCTGAGGTTA,AAAGATGTGTTTC,gRNA_CDK6_targ_8408,gRNA_CDK4_targ_7887,F3-R3,F3-R3,False
30,CDK3_15,GGTTAAAAGTCAGCATTTCC,GGGCTCATAAGTT,GGGCTCATAAGTT,gRNA_CDK4_targ_7465,gRNA_CDK4_targ_7465,F3-R3,F3-R3,True

In [24]:
#colony_seq.to_csv('colony_seq_identification.csv')

In [17]:
np.unique(colony_seq['proto_bc_match'], return_counts=True)

(array([False,  True]), array([14, 17]))

# Primordium identification

In [33]:
primordium = pd.read_csv('primordium_seqs.csv')

primordium['Protospacer'] = [i.upper() for i in primordium['Protospacer']]
primordium['Sensor'] = [i.upper() for i in primordium['Sensor']]
primordium['Barcode'] = [i.upper() for i in primordium['Barcode']]

primordium

,Sample ID,Protospacer,Sensor,Barcode
0,CDK1.1,GAGGGCGTCATCGCTGTCGA,CTGCCCAGCGCATCGACAGCGATGGCGCCCTCAACACGACTA,ACCCTGAAGAGTG
1,CDK1.2,GGTTTGCGCCTGAAGGCCCT,GAAGCCACTGCTAGGGCCTTCAGGCGCAAACTCAGGTGGACC,TTCTACTGGCGTC
2,CDK1.3,GCGGCATGTAGAGAAATAGC,ACTTCACTTACTGCTATTTCTCTACATGCCGACATAGAGATC,CGCTGGAAAGCGT
3,CDK1.4,GCTGAGCAGCGAGCGGGAGC,GATGGGGCTGCGGGTCCACATCTCTGCCATGATGCACCCAGC,AATAGGTGCAAGT
4,CDK1.5,GAACTGGATCGGATATTTAG,AACCCCATGACACTAAATATCCGATCCAGTTGATCATGATGA,GGCGTGTTGGTCG
5,CDK2.1,GCGGCTGCAGGAGCGGCAAC,GCCGCCGCTGCTGTTGCCGCTCCTGCAGCCGCAGCTCCTGCA,CCTTCATATTCAA
6,CDK2.2,GTTCTTTGGTTTCACCATAG,CTTCTGCCGCCCTCCTGCGCGCCTCTTGCCTCTCGCCAGCCG,ATCAACATCGTGT
7,CDK2.3,GTTGGCAGTTCTCTTGAGTC,CTCTTCTGCTCCTTATGTTAGCAATGATGGTCTAGGAAGCAG,TATTGAGAGTGCG
8,CDK2.4,GTATGGAAAACTCTATCGGG,CACTTTGATTCAGCTGTTGTGTGATGTCAGCAAGGCCTGTTG,GTGGTCTGGGTAC
9,CDK2.5,GACCCTCATGCCGGAGTGAA,AACAGGGCTGCCTTCACTCCGGCATGAGGGTCAGTTAATGAA,AGCCACTTAGAAA
10,CDK3.1,GAGCAGATTCTGAGGTTTAA,TCCACCGAGACCTTAAACCTCAGAATCTGCTTATTAACACAG,TCACAAATGTCGG
11,CDK3.2,GTTCATGGAGAACTTCCAAA,TCTTTTCCACCTTTTGGAAGTTCTCCATGAAGCGCCAGCGAG,TTATGCAGCATGT
12,CDK3.3,GGACCCTAACAAGCGGATTT,CTGCCTTGGCCGAAATCCGCTTGTTAGGGTCGTAGTGCAGCA,CAAATGTGGTCTG
13,CDK3.4,GGGATCTCTGGAGTGTTGGC,TGGTCGGCTTCAGAGTTTCCACAGAAGAGAGGCCTAAGGTGA,TGTCTGGCGCATT
14,CDK3.5,GACTAACGCCGCTCCTACAG,GGTTGGTGTCGTTTGCGGTTCTTGCGTTAGCTGCGCGTCTGG,CTCGGGAGCTAAT

In [34]:
proto_id = []
bc_id = []
proto_pool = []
sensor_id = []
bc_pool = []
bc_predicted = []
for i, val in primordium.iterrows():
    p = val['Protospacer']
    b = val['Barcode']
    s = val['Sensor']

    proto = library.loc[library['proto_G+19']==p, 'gRNA_id']
    bc = library.loc[library['Hamming_BC']==b, 'gRNA_id']
    sensor = library.loc[library['sensor_wt']==s, 'gRNA_id']

    if len(proto)!=0:
        proto_id.append(proto.values[0])
        proto_pool.append(library.loc[library['proto_G+19']==p, 'Pool'].values[0])
        bc_predicted.append(library.loc[library['proto_G+19']==p, 'Hamming_BC'].values[0])
    elif len(proto)==0:
        proto_id.append(None)
        proto_pool.append(None)
        bc_predicted.append(None)

    if len(sensor)!=0:
        sensor_id.append(sensor.values[0])
        
    elif len(sensor)==0:
        sensor_id.append(None)
        

    if len(bc)!=0:
        bc_id.append(bc.values[0])
        bc_pool.append(library.loc[library['Hamming_BC']==b, 'Pool'].values[0])
    elif len(bc)==0:
        bc_id.append(None)
        bc_pool.append(None)

In [35]:
primordium['barcode_predicted'] = bc_predicted
primordium['proto_id'] = proto_id
primordium['bc_id'] = bc_id
primordium['sensor_id'] = sensor_id
primordium['proto_pool'] = proto_pool
primordium['bc_pool'] = bc_pool


match = []

for i, val in primordium.iterrows():
    if val['proto_id']==val['bc_id']:
        match.append(True)
    else:
        match.append(False)

primordium['proto_bc_match'] = match
primordium

,Sample ID,Protospacer,Sensor,Barcode,barcode_predicted,proto_id,bc_id,sensor_id,proto_pool,bc_pool,proto_bc_match
0,CDK1.1,GAGGGCGTCATCGCTGTCGA,CTGCCCAGCGCATCGACAGCGATGGCGCCCTCAACACGACTA,ACCCTGAAGAGTG,AACCCTGACGAGT,gRNA_CDK9_targ_1660,None,None,F1-R1,None,False
1,CDK1.2,GGTTTGCGCCTGAAGGCCCT,GAAGCCACTGCTAGGGCCTTCAGGCGCAAACTCAGGTGGACC,TTCTACTGGCGTC,TTCTACTGGCGTC,gRNA_CDK19_targ_6316,gRNA_CDK19_targ_6316,None,F1-R1,F1-R1,True
2,CDK1.3,GCGGCATGTAGAGAAATAGC,ACTTCACTTACTGCTATTTCTCTACATGCCGACATAGAGATC,CGCTGGAAAGCGT,CGCTGGAAAGCGT,gRNA_CDK8_targ_489,gRNA_CDK8_targ_489,gRNA_CDK8_targ_489,F1-R1,F1-R1,True
3,CDK1.4,GCTGAGCAGCGAGCGGGAGC,GATGGGGCTGCGGGTCCACATCTCTGCCATGATGCACCCAGC,AATAGGTGCAAGT,CTGGCGGGTGACT,gRNA_CDK8_targ_440,gRNA_CDK9_targ_1265,gRNA_CDK9_targ_1265,F1-R1,F1-R1,False
4,CDK1.5,GAACTGGATCGGATATTTAG,AACCCCATGACACTAAATATCCGATCCAGTTGATCATGATGA,GGCGTGTTGGTCG,GGCGTGTTGGTCG,gRNA_CDK19_targ_6768,gRNA_CDK19_targ_6768,gRNA_CDK19_targ_6768,F1-R1,F1-R1,True
5,CDK2.1,GCGGCTGCAGGAGCGGCAAC,GCCGCCGCTGCTGTTGCCGCTCCTGCAGCCGCAGCTCCTGCA,CCTTCATATTCAA,CCTTCATATTCAA,gRNA_CDK13_targ_5155,gRNA_CDK13_targ_5155,gRNA_CDK13_targ_5155,F2-R2,F2-R2,True
6,CDK2.2,GTTCTTTGGTTTCACCATAG,CTTCTGCCGCCCTCCTGCGCGCCTCTTGCCTCTCGCCAGCCG,ATCAACATCGTGT,AACTCGCATTCAC,gRNA_CDK13_targ_5746,gRNA_CDK13_targ_4052,gRNA_CDK13_targ_4052,F2-R2,F2-R2,False
7,CDK2.3,GTTGGCAGTTCTCTTGAGTC,CTCTTCTGCTCCTTATGTTAGCAATGATGGTCTAGGAAGCAG,TATTGAGAGTGCG,GTTGTAGTGAGCG,gRNA_CDK12_targ_2561,gRNA_CDK13_targ_6156,gRNA_CDK13_targ_6156,F2-R2,F2-R2,False
8,CDK2.4,GTATGGAAAACTCTATCGGG,CACTTTGATTCAGCTGTTGTGTGATGTCAGCAAGGCCTGTTG,GTGGTCTGGGTAC,GCCGGAGAAAGCT,gRNA_CDK12_targ_2773,gRNA_CDK12_targ_2491,gRNA_CDK12_targ_2491,F2-R2,F2-R2,False
9,CDK2.5,GACCCTCATGCCGGAGTGAA,AACAGGGCTGCCTTCACTCCGGCATGAGGGTCAGTTAATGAA,AGCCACTTAGAAA,AGCCACTTAGAAA,gRNA_CDK13_targ_4972,gRNA_CDK13_targ_4972,gRNA_CDK13_targ_4972,F2-R2,F2-R2,True
10,CDK3.1,GAGCAGATTCTGAGGTTTAA,TCCACCGAGACCTTAAACCTCAGAATCTGCTTATTAACACAG,TCACAAATGTCGG,TCACAAATGTCGG,gRNA_CDK2_targ_7300,gRNA_CDK2_targ_7300,gRNA_CDK2_targ_7300,F3-R3,F3-R3,True
11,CDK3.2,GTTCATGGAGAACTTCCAAA,TCTTTTCCACCTTTTGGAAGTTCTCCATGAAGCGCCAGCGAG,TTATGCAGCATGT,TTATGCAGCATGT,gRNA_CDK2_targ_6973,gRNA_CDK2_targ_6973,gRNA_CDK2_targ_6973,F3-R3,F3-R3,True
12,CDK3.3,GGACCCTAACAAGCGGATTT,CTGCCTTGGCCGAAATCCGCTTGTTAGGGTCGTAGTGCAGCA,CAAATGTGGTCTG,CAAATGTGGTCTG,gRNA_CDK2_targ_7179,gRNA_CDK2_targ_7179,gRNA_CDK2_targ_7179,F3-R3,F3-R3,True
13,CDK3.4,GGGATCTCTGGAGTGTTGGC,TGGTCGGCTTCAGAGTTTCCACAGAAGAGAGGCCTAAGGTGA,TGTCTGGCGCATT,CACTCTGGATACT,gRNA_CDK6_targ_8301,gRNA_CDK4_targ_7781,gRNA_CDK4_targ_7781,F3-R3,F3-R3,False
14,CDK3.5,GACTAACGCCGCTCCTACAG,GGTTGGTGTCGTTTGCGGTTCTTGCGTTAGCTGCGCGTCTGG,CTCGGGAGCTAAT,TACGCGCTTTCAG,gRNA_nt_8812,gRNA_nt_9178,gRNA_nt_8812,F1-R1,F3-R3,False

In [40]:
library[library['proto_G+19']=='GTTCTTTGGTTTCACCATAG']

,gRNA_id,Gene,protospacer,proto_G+19,chrom,exon,proto_start,proto_end,PAM,PAM_start,...,CDS_hit,ABE_amenable,CBE_amenable,classification,nearest_exon_distance,Pool,Hamming_BC,gRNA_oligo,RE_sites,gRNA_id_OLD
5745,gRNA_CDK13_targ_5746,CDK13,TTTCTTTGGTTTCACCATAG,GTTCTTTGGTTTCACCATAG,7.0,4,39999395.0,39999376.0,CG,39999374.0,...,True,False,True,targeting,NaN,F2-R2,AACTCGCATTCAC,GTGTAACCCGTAGGGCACCTAGCGTACACGTCTCACACCGTTCTTT...,2,gRNA_1827